# Generated by Django 4.2.5 on 2023-09-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_bs', models.CharField(max_length=10)),
                ('year_in_ad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('province', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_government', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_of_total_estimates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.fiscalyear')),
            ],
        ),
    ]
